AlgoriParams:
    is_enemy_red: True
    ch1_min_r: 14
    ch1_max_r: 240
    ch1_min_b: 190
    ch1_max_b: 255
    ch2_min: 40
    ch2_max: 255
    ch3_min_r: 200
    ch3_max_r: 255
    ch3_min_b: 40
    ch3_max_b: 200

CameraParams:
    rows: 480
    cols: 640
    fps: 100
    cx: 317.2613
    cy: 243.82
    fx: 442.2
    fy: 414.46
    distcoef1: -0.0906
    distcoef2: 0.0882

MarkerParams:
    contours_lengtch1_min:  10    #LED contour size
    contours_lengtch1_max:  250
    LED_ratio_min:  2        # chang div kuan
    LED_ratio_max:  20
    LED_widtch1_min:  7        # width in pixel
    LED_widtch1_max:  100
    marker_parallel_angle:  6     # angle between 2 led
    marker_vertical_angle:  10     # no use
    marker_direction_angle:  40    # angle between c2c and horizon
    marker_ratio_min:  0.8    #  width / height
    marker_ratio_max:  5
    marker_size_min:  10    #  c2c distance
    marker_size_max:  200

is_record: False
ifshow: True
if_calc_depth: False
if_analyze_motion: True
