AlgoriParams:
    is_enemy_red: True
    h_min_r: 14
    h_max_r: 240
    h_min_b: 220
    h_max_b: 255
    s_min: 40
    s_max: 255
    v_min: 200
    v_max: 255

CameraParams:
    cx: 317.2613
    cy: 243.82
    fx: 442.2
    fy: 414.46
    distcoef1: -0.0906
    distcoef2: 0.0882

is_record: False
ifshow: True
